### ISSUE TITLE
Please actually publish the codebase

### ISSUE THREAD

**Issue by bmorphism** [shizhediao/active-prompt#1]
Happy to trial running the code in whatever state! Was excited to see the repository, but surprised not to see any (as of writing) actual code 😔

**Comment by shizhediao** [comment]
Hi,
Thanks for your attention!
We are working on the code cleaning. The code will be released soon.
Please stay tuned! 🤗

**Comment by shizhediao** [comment]
We have released the code with dataset. 
This issue will be closed. Feel free to open another one if you have further questions.
Thanks
