### ISSUE TITLE
Why select large uncertainty as the candidates? It seems to not that intuitive?

### ISSUE THREAD

**Issue by A11en0** [shizhediao/active-prompt#2]
<img width="583" alt="image" src="https://github.com/shizhediao/active-prompt/assets/33925232/f0501649-daeb-45b0-a4e4-e3887640b5ff">

**Comment by shizhediao** [comment]
Hi, 
Thanks for your attention to our work.
Our proposed method is motivated by finding the most uncertain questions which help improve the performance equipped with human annotations.
Therefore, we introduce several different uncertainty metrics. As one of them, the larger the entropy, the higher the uncertainty, so we want to select those questions with larger entropy.

**Comment by A11en0** [comment]
I get it, thanks a lot.

**Comment by shizhediao** [comment]
You are welcome! 
This issue is closed. Feel free to open another one if you have further questions.
Thanks!
