### ISSUE TITLE
Using Active prompt for custom question

### ISSUE THREAD

**Issue by heidage** [shizhediao/active-prompt#3]
I would like to use active prompts for one of my use case. However, I have my own question and answers for the few-shot CoT. How could I do that using this repo?

Thank you very much!

**Comment by shizhediao** [comment]
Hi,
Please take a look at [load_data](https://github.com/shizhediao/active-prompt/blob/main/utils.py#L89) to modify the data processing according to your own Q&A.
Please feel free to ask if you have further questions.
Thanks!

**Comment by heidage** [comment]
Hi, I saw the load_data function, and I would like to clarify that if i do not specify any dataset, the questions and answers would be an empty lsit? and I would have to create a way to populate question and answers list?

Thank you!

**Comment by shizhediao** [comment]
Hi,
the questions and answers in the load_data function are exemplars for in-context learning (few-shot).
feel free to modify this function by adding your example questions and answers.
